<a href="https://www.kaggle.com/code/mdraiesh9648/exploratory-data-analysis?scriptVersionId=108766543" target="_blank"><img align="left" alt="Kaggle" title="Open in Kaggle" src="https://kaggle.com/static/images/open-in-kaggle.svg"></a>

# Exploratory data analysis with Python

# Python Pandas

In [1]:
import pandas as pd

In [2]:
df = pd.read_csv("../input/customer-segmentation-tutorial-in-python/Mall_Customers.csv")

In [3]:
df.head()

   CustomerID  Gender  Age  Annual Income (k$)  Spending Score (1-100)
0           1    Male   19                  15                      39
1           2    Male   21                  15                      81
2           3  Female   20                  16                       6
3           4  Female   23                  16                      77
4           5  Female   31                  17                      40

In [4]:
s1 = pd.Series([1,2,3,4,5])
s1

0    1
1    2
2    3
3    4
4    5
dtype: int64

In [5]:
type(s1)

pandas.core.series.Series

In [6]:
s1 = pd.Series([1,2,3,4,5],index=['a','b','c','d','e'])

In [7]:
s1

a    1
b    2
c    3
d    4
e    5
dtype: int64

In [8]:
s1 = pd.Series({'a':10,'b':20,'c':30})

In [9]:
s1

a    10
b    20
c    30
dtype: int64

In [10]:
s1 = pd.Series({'a':10,'b':20,'c':30}, index=['b','c','d','a'])

In [11]:
s1

b    20.0
c    30.0
d     NaN
a    10.0
dtype: float64

### Extracting individual elements

In [12]:
s1 = pd.Series([1,2,3,4,5,6,7,8,9])
s1[3]

4

In [13]:
s1[:4]

0    1
1    2
2    3
3    4
dtype: int64

In [14]:
s1[-3:]

6    7
7    8
8    9
dtype: int64

### Basic Math Operations on Series

In [15]:
s1+5

0     6
1     7
2     8
3     9
4    10
5    11
6    12
7    13
8    14
dtype: int64

In [16]:
# Adding two series objects

s2 = pd.Series([10,20,30,40,50,60,70,80,90])
s1+s2

0    11
1    22
2    33
3    44
4    55
5    66
6    77
7    88
8    99
dtype: int64

### Creating Dataframe

In [17]:
import pandas as pd
pd.DataFrame({"Name":['Bob','Sam','Anne'],"Marks":[76,89,97]})

   Name  Marks
0   Bob     76
1   Sam     89
2  Anne     97

In [18]:
iris = pd.read_csv('../input/iris-dataset-new/iris.csv')

In [19]:
iris.head()

   Sales  Profit  Price     Month Species
0     19      40    194   January     Low
1     54      43    573  February    High
2     53      38    819     March  Medium
3     54      23    227     April     Low
4     81      20    650       May    High

In [20]:
iris.tail()

    Sales  Profit  Price  Month Species
14     83      42    988  March  Medium
15     85      19    495  April    High
16     15      62    942    May    High
17     93      94    525   June     Low
18     51      29    329   July  Medium

In [21]:
iris.shape

(19, 5)

In [22]:
iris.describe()

           Sales     Profit       Price
count  19.000000  19.000000   19.000000
mean   56.684211  53.157895  515.052632
std    28.120875  23.746960  274.265377
min    15.000000  19.000000  122.000000
25%    27.000000  39.000000  278.000000
50%    54.000000  45.000000  525.000000
75%    82.000000  68.000000  669.000000
max    95.000000  98.000000  988.000000

### .iloc[] function

In [23]:
iris.iloc[0:3,0:2]

   Sales  Profit
0     19      40
1     54      43
2     53      38

In [24]:
# .loc[] function

iris.loc[(5,10),("Sales","Month")]

    Sales     Month
5      57      June
10     20  November

In [25]:
iris.loc[3:9,("Profit","Price")]

   Profit  Price
3      23    227
4      20    650
5      55    122
6      45    128
7      45    619
8      73    225
9      69    359

In [26]:
# Dropping Columns

iris.drop('Profit',axis=1)

    Sales  Price      Month Species
0      19    194    January     Low
1      54    573   February    High
2      53    819      March  Medium
3      54    227      April     Low
4      81    650        May    High
5      57    122       June     Low
6      95    128       July    High
7      90    619     August  Medium
8      78    225  September     Low
9      22    359    October  Medium
10     20    615   November     Low
11     73    403   December    High
12     28    885    January  Medium
13     26    688   February     Low
14     83    988      March  Medium
15     85    495      April    High
16     15    942        May    High
17     93    525       June     Low
18     51    329       July  Medium

In [27]:
# Dropping Rows

iris.drop([2,4,7,9],axis=0)

    Sales  Profit  Price      Month Species
0      19      40    194    January     Low
1      54      43    573   February    High
3      54      23    227      April     Low
5      57      55    122       June     Low
6      95      45    128       July    High
8      78      73    225  September     Low
10     20      83    615   November     Low
11     73      65    403   December    High
12     28      67    885    January  Medium
13     26      98    688   February     Low
14     83      42    988      March  Medium
15     85      19    495      April    High
16     15      62    942        May    High
17     93      94    525       June     Low
18     51      29    329       July  Medium

### Mean, median, maximum, ,minimum functions

In [28]:
iris.mean()

/opt/conda/lib/python3.7/site-packages/ipykernel_launcher.py:1: FutureWarning: Dropping of nuisance columns in DataFrame reductions (with 'numeric_only=None') is deprecated; in a future version this will raise TypeError.  Select only valid columns before calling the reduction.
  """Entry point for launching an IPython kernel.

Sales      56.684211
Profit     53.157895
Price     515.052632
dtype: float64

In [29]:
iris.min()

Sales         15
Profit        19
Price        122
Month      April
Species     High
dtype: object

In [30]:
iris.median()

/opt/conda/lib/python3.7/site-packages/ipykernel_launcher.py:1: FutureWarning: Dropping of nuisance columns in DataFrame reductions (with 'numeric_only=None') is deprecated; in a future version this will raise TypeError.  Select only valid columns before calling the reduction.
  """Entry point for launching an IPython kernel.

Sales      54.0
Profit     45.0
Price     525.0
dtype: float64

In [31]:
iris.max()

Sales             95
Profit            98
Price            988
Month      September
Species       Medium
dtype: object

### More pandas function

In [32]:
def half(s):
    return s*0.5

iris[['Sales','Profit','Price']].apply(half)

    Sales  Profit  Price
0     9.5    20.0   97.0
1    27.0    21.5  286.5
2    26.5    19.0  409.5
3    27.0    11.5  113.5
4    40.5    10.0  325.0
5    28.5    27.5   61.0
6    47.5    22.5   64.0
7    45.0    22.5  309.5
8    39.0    36.5  112.5
9    11.0    34.5  179.5
10   10.0    41.5  307.5
11   36.5    32.5  201.5
12   14.0    33.5  442.5
13   13.0    49.0  344.0
14   41.5    21.0  494.0
15   42.5     9.5  247.5
16    7.5    31.0  471.0
17   46.5    47.0  262.5
18   25.5    14.5  164.5

In [33]:
def double(s):
    return s*2

iris[['Sales','Profit','Price']].apply(double)

    Sales  Profit  Price
0      38      80    388
1     108      86   1146
2     106      76   1638
3     108      46    454
4     162      40   1300
5     114     110    244
6     190      90    256
7     180      90   1238
8     156     146    450
9      44     138    718
10     40     166   1230
11    146     130    806
12     56     134   1770
13     52     196   1376
14    166      84   1976
15    170      38    990
16     30     124   1884
17    186     188   1050
18    102      58    658

### value_counts() function

In [34]:
iris['Species'].value_counts()

Low       7
High      6
Medium    6
Name: Species, dtype: int64

In [35]:
iris.sort_values(by='Profit')

    Sales  Profit  Price      Month Species
15     85      19    495      April    High
4      81      20    650        May    High
3      54      23    227      April     Low
18     51      29    329       July  Medium
2      53      38    819      March  Medium
0      19      40    194    January     Low
14     83      42    988      March  Medium
1      54      43    573   February    High
6      95      45    128       July    High
7      90      45    619     August  Medium
5      57      55    122       June     Low
16     15      62    942        May    High
11     73      65    403   December    High
12     28      67    885    January  Medium
9      22      69    359    October  Medium
8      78      73    225  September     Low
10     20      83    615   November     Low
17     93      94    525       June     Low
13     26      98    688   February     Low